### ISSUE TITLE
Where I put this?

### ISSUE THREAD

**Issue by thearabbit** [SimonSimCity/meteor-client-session-timeout#1]
I would like to `auto logout` after inactive `5 min`
I base on `Meteor + Vue`

**Comment by SimonSimCity** [comment]
There's nothing really view-related - so it doesn't matter if you use `vue`, `angular`, `blaze` or another framework.

Just put the code I wrote in the `README.md` into your `client/main.js` or a file directly included in there. This code should be executed as soon as the client code is loaded. I'll add a note there.

Does this answer your question?

**Comment by thearabbit** [comment]
Thanks I will try

**Comment by SimonSimCity** [comment]
I guess the try was successful 😜
